# Generated by Django 4.1.1 on 2022-09-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
