# Generated by Django 4.1.1 on 2022-09-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
