# Generated by Django 4.1.1 on 2022-10-12 20:53

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_poll_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=200, validators=[polls.models.only_characters_validator]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(blank=True, max_length=200, validators=[polls.models.only_characters_validator]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=100, validators=[polls.models.only_characters_validator]),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200, validators=[polls.models.only_characters_validator]),
        ),
    ]
