# Generated by Django 4.1.1 on 2022-10-17 22:51

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_answer_text_alter_poll_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200, validators=[polls.models.question_validator]),
        ),
    ]
