# Generated by Django 4.1.1 on 2022-10-11 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_creation_date_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 18, 21, 53, 979181, tzinfo=datetime.timezone.utc), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
