# Generated by Django 4.1.1 on 2022-10-18 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 17, 5, 43, 58002, tzinfo=datetime.timezone.utc), verbose_name='creation date'),
        ),
    ]
